spring.application.name=OpenCV
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Kjc00011978!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#jpa:
#hibernate:
#ddl-auto:update
#show-sql:true
#mail:
#host:smtp.mail.ru
#port:465
#username:YOUR_MAIL@mail.ru
#password:YOUR_MAIL_PASSWORD
#properties:
#mail:
#smtp:
#auth:true
#ssl:
#enable:true
